### ISSUE TITLE
Keluhan fungsi pada HG680P

### ISSUE THREAD

**Issue by risunCode** [rtaserver/RTA-WRT#1]
- TinyFM search
sudah coba di upgrade tetap tidak work untuk fungsi search
![tinyfm-not-work](https://github.com/user-attachments/assets/36553b52-c4ad-4725-bdac-f2622f0433a9)
- Terminal ini worek tapi** kenapa begitu wkw
![terminal-hmm-why](https://github.com/user-attachments/assets/223be012-8e2a-425b-80d8-d4c8a50357fa)

### Detil perangkat dan firmware yang digunakan
- jam stb sudah sinkron
- HG680P 2GB Ram
- [Firmware yang digunakan - RTA-WRT_Amlogic_HG680P_k5.15.167_2024.10.04_openclash-passwall.img.gz](https://github.com/rtaserver/RTA-WRT/releases/download/23.05.5-amlogic-20241004/RTA-WRT_Amlogic_HG680P_k5.15.167_2024.10.04_openclash-passwall.img.gz)
![system-detail](https://github.com/user-attachments/assets/d7c9ac6f-a453-4a71-a689-05d2b86c4f97)

# Request
- Update yacd dashboard ke meta yacd yang baru
Overall ini bagus tunnelnya sudah lengkap semua, hanya itu saja kendalanya.
terimakasih

**Comment by rtaserver** [comment]
ok mas. masalah terminal saya lupa kemaren. 
untuk yacd ada foto referensi ? perasaan itu dah meta bawaan oc atau maunya yang mod ?

**Comment by risunCode** [comment]
hmm yacdnya tampilan yang lama..
bukan yacd meta..
browser udah ganti + clear cache buat mastikan itu yacd bukan dari fw yang sebelumnya

# tampilan yacd yang saya maksud lama
![1image](https://github.com/user-attachments/assets/0a800fc3-8540-420e-8713-ab9422fd64c9)

# tampilan yacd meta
![image](https://github.com/user-attachments/assets/3f8ab470-004a-47bf-8c2f-e909b1434de0)

secara fungsi sih nggak ngaruh wkwk.. cuma biar keren dikit aja 🤣 
oh iya terimakasih sudah direspon 👍 🥇

**Comment by rtaserver** [comment]
Dah Fixed Buat TinyFm Sama Terminal nya
